version: '3.8'

services:
  db:
    image: sectorsync-db
    container_name: postgresql_sectorsync
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sectorsync
    ports:
      - "5432:5432"

volumes:
  sectorsync_data: