version: '3.8'

services:
  db:
    image: postgres
    container_name: postgresql_sectorsync
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sectorsync
    ports:
      - "5432:5432"
    volumes:
      - sectorsync_data:/var/lib/postgresql/data

volumes:
  sectorsync_data: