server:
  error:
    include-stacktrace: on_param
  servlet:
    context-path: /sectorsync/api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sectorsync?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

springdoc:
  swagger-ui:
    path: /public/swagger